### ISSUE TITLE
Gesture toggle loss and right-shift not registered.

### ISSUE THREAD

**Issue by MIKUiqnw0** [Killers0992/VRCBonesController#1]
- When enabling the system, gestures lose their ability to toggle and instead become 'push and hold' regardless of whether it's enabled or not.
- The mod doesn't register right shift as it's own expression when attempting to gesture. eg, A user keys in RShift + F6 to get the 5th or 6th gesture, it causes the mod to undesirably enable rather than perform the gesture.

**Comment by Killers0992** [comment]
Should be fixed in latest release
